[package]
name = "ztsec_load_test"
version = "1.0.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
base64 = "0.22.1"
ed25519-dalek = "=2.2.0"
futures-util = "0.3.34"
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
tokio-tungstenite = { version = "=0.30.0", default-features = false, features = ["connect", "handshake"] }
ztsec_protocol = { path = "../../protocol" }
