[package]
name = "ztsec_server"
version = "1.0.0"
edition = "2024"
rust-version = "1.92"
license = "MIT"

[dependencies]
arti-client = { path = "../vendor/arti/crates/arti-client", version = "0.46.0", default-features = false, features = ["tokio", "native-tls", "onion-service-service"] }
base64 = "0.22.1"
ed25519-dalek = "=2.2.0"
futures-util = "0.3.34"
getrandom = "=0.2.17"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "macros", "net", "time", "sync", "signal", "io-util"] }
tokio-tungstenite = { version = "=0.30.0", default-features = false, features = ["handshake"] }
tor-cell = { path = "../vendor/arti/crates/tor-cell", version = "0.46.0", features = ["hs"] }
tor-hsservice = { path = "../vendor/arti/crates/tor-hsservice", version = "0.46.0", default-features = false, features = ["tor-rtcompat/tokio", "tor-rtcompat/native-tls"] }
tor-proto = { path = "../vendor/arti/crates/tor-proto", version = "0.46.0", default-features = false, features = ["hs-service", "tokio"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
tor-rtcompat = { path = "../vendor/arti/crates/tor-rtcompat", version = "0.46.0", default-features = false, features = ["tokio", "native-tls"] }
ztsec_protocol = { path = "../protocol" }

